permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
          {
            "clientId": "14f96396-240d-4b4a-a8a7-ef763d077ee2",
            "clientSecret": "${{ secrets.az_secret }}",
            "tenantId": "2e08cf7f-8ba4-4151-bed9-f1b316f95dd9",
            "subscriptionId": "158934aa-48ae-4aa1-bae5-78194afd79f3"
          }

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan