name: Terraform Azure Deployment

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: ./Environment/prod

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: "14f96396-240d-4b4a-a8a7-ef763d077ee2"
          tenant-id: "2e08cf7f-8ba4-4151-bed9-f1b316f95dd9"
          subscription-id: "158934aa-48ae-4aa1-bae5-78194afd79f"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan